### ISSUE TITLE
create query vinyl inventory function(hard code)

### ISSUE THREAD

**Issue by kithe-raker** [kithe-raker/gimmesong#63]
Create a function that allow user to query the vinyl from inventory
but since there are limited time, I decided to hard code this part for the sake of deliver speed

**DOD**
- [x] create vinyl style in db(background and center component)
- [x] hard code list of vinyl

**Comment by kithe-raker** [comment]
@athensclub I've create a function to query all vinyl styles from user's inventory, but not yet add vinyl style. Have a look in c99082b5229f8b92d78e2573b4f8e9367e3071a1
.
I'll add the vinyl style tmrw

**Comment by athensclub** [comment]
I've tried implementing the rendering all available vinyl style. Currently there is still issue that the vinyl list will resize itself to make all children fit inside it (no scrolling).
