### ISSUE TITLE
More themes (Christmas) for Share Widget

### ISSUE THREAD

**Issue by athensclub** [kithe-raker/gimmesong#67]
I forgot to open this issue. This will introduce more share widget to be deployed for Christmas.

**DOD**
 - [x] **New Theme 1** (Cream background with Santa hat decoration)
 - [x] **New Theme 2** (Pink background with gift box & notes decoration)

**Comment by athensclub** [comment]
Yeah, I'm new to GitHub. Anyways,

**Theme 1 without user tag**
![gimmesong-1671371569740](https://user-images.githubusercontent.com/43963760/208302811-d20cb071-2c8f-41f1-892b-2b13225eb31b.png)


**Theme 1 with user tag**
![gimmesong-1671371528220](https://user-images.githubusercontent.com/43963760/208302797-ef29b0ce-da34-4da9-a0e9-3620b5a88954.png)

**Theme 2 without user tag**
![gimmesong-1671371565077](https://user-images.githubusercontent.com/43963760/208302806-bcedf405-4c16-455d-b853-43c11e1cd519.png)


**Theme 2 with user tag**
![gimmesong-1671371524828](https://user-images.githubusercontent.com/43963760/208302789-f9b0c3de-d1bf-4b75-9ed9-f43f2ba1ea22.png)

**Comment by kithe-raker** [comment]
done #72
