### ISSUE TITLE
Share widget for Christmas Event

### ISSUE THREAD

**Issue by athensclub** [kithe-raker/gimmesong#84]
There's a lot of adjustments regarding the Christmas Event. I created this issue to handle features related to sharing in Christmas Event.

**DOD**
 - [x] New (actually old) pink share pattern for Christmas Theme
 - [x] Show Christmas share pattern only for Christmas Theme disc

**Comment by athensclub** [comment]
@kithe-raker I've implemented conditional rendering where the Christmas share pattern will only show if the disc to share has Santa or Present box as center. But I feel that this feels unintuitive for the user, because when the song is played, the center become the song's cover, and the user can't tell which disc is a Christmas Theme disc. Any Ideas?

**Comment by kithe-raker** [comment]
> @kithe-raker I've implemented conditional rendering where the Christmas share pattern will only show if the disc to share has Santa or Present box as center. But I feel that this feels unintuitive for the user, because when the song is played, the center become the song's cover, and the user can't tell which disc is a Christmas Theme disc. Any Ideas?

make sense, need to discuss with the team

**Comment by kithe-raker** [comment]
> > @kithe-raker I've implemented conditional rendering where the Christmas share pattern will only show if the disc to share has Santa or Present box as center. But I feel that this feels unintuitive for the user, because when the song is played, the center become the song's cover, and the user can't tell which disc is a Christmas Theme disc. Any Ideas?
> 
> make a good point, need to discuss with the team

working in #86
