### ISSUE TITLE
Rename vinyl style's component(webapp)

### ISSUE THREAD

**Issue by kithe-raker** [kithe-raker/gimmesong#85]
I want to rename the vinyl style component to the name that is more straight forward, to avoid the confusion in the future. 
I want to rename 
- `background` -> `disc`
- `center` -> `emoji`

DOD
- [x] rename style component in SDK
- [x] rename style component in context
- [x] rename in the UI

**Comment by kithe-raker** [comment]
@athensclub I've just rename the vinyl style component.
But I haven't rename in the UI yet, need your help to do this part since you are the author of the UI part

**Comment by athensclub** [comment]
Ok I will get into it soon. I'm kinda busy right now

**Comment by kithe-raker** [comment]
> Ok I will get into it soon. I'm kinda busy right now

Ok mate, just inform you in case that there're some part of UI that may not render properly.

**Comment by athensclub** [comment]
I believed I have handle all of renaming in https://github.com/kithe-raker/gimmesong/commit/e0c950c553f048067ff039ae92182cba74d3b2f1

**Comment by athensclub** [comment]
Ah I still forgot to rename in the DiscList component. Going to fix it now

**Comment by athensclub** [comment]
Ok. I finished renaming in DiscList component but found something and got very curious. I have just started testing at around 22:00 and noticed that every disc that is sent before I started testing and they all have the default emoji, even though I sent that disc with Santa or present emoji, but every disc I sent after I started testing (22:00) works fine.

**Comment by kithe-raker** [comment]
> Ok. I finished renaming in DiscList component but found something and got very curious. I have just started testing at around 22:00 and noticed that every disc that is sent before I started testing and they all have the default emoji, even though I sent that disc with Santa or present emoji, but every disc I sent after I started testing (22:00) works fine.

that's normal. Because the database is store the style as 
```
{
   center: "string"
}
```
but the new version is
```
{
   emoji: "string"
}
```
so when cannot find the `emoji` value in the old version
