### ISSUE TITLE
Flippable Song Disc (Switch between emoji center and song cover center) in My Songs page

### ISSUE THREAD

**Issue by athensclub** [kithe-raker/gimmesong#86]
There is a Christmas Event where the user can use special share pattern if the disc that is shared is a Christmas disc. But this feels very unintuitive for the user because when a song is played, the center will become song's cover, so the user doesn't know which disc is a Christmas disc. This issue aims to fix that by allowing user to double-tap on songs to switch between emoji center and song cover center.

**DOD**
- [x] double-tap on song discs to switch between emoji center and song cover center
- [x] flipping animation 
- [x] double tapping on song that haven't been played will automatically play the song

See:
https://www.npmjs.com/package/react-card-flip
https://www.npmjs.com/package/use-double-click

**Comment by athensclub** [comment]
I've been struggling with what should've been a simple task. I'm trying to make the site automatically play the song that is being flipped (that hasn't been played before). When I inspected the code, I see that there is no way to play a specific song. I must first set the current song to the specific song, then toggle the play. The problem is that when I set the current song (using `setCurrent()`, updating the state) then toggle the play (using `handleToggle()` function), The current state doesn't update immediately so the toggle play will not have current (it will still be old value) song to play. I've tried using this: https://medium.com/geekculture/usecallbackstate-the-hook-that-let-you-run-code-after-a-setstate-operation-finished-25f40db56661 But it doesn't work. I've tried a few other similar methods with no success. Maybe I don't understand React well enough.  Any Ideas? Or is there a simpler way to play a specific song?

**Comment by athensclub** [comment]
I've finished making the unplayed song play when it is flipped (you can review with video in discord see: https://discord.com/channels/1041235400494157886/1041239741829492806/1055427202772111390). But I also found another issue: some videos are not available to play (see image below), but is an option to the user and we aren't handling this. This means that it will show as if the song is playable, but nothing will happens when the play button is click (also happens in production, video in discord see: https://discord.com/channels/1041235400494157886/1041239741829492806/1055423643875823626)

**This song is unavailable but is an option that can be sent**
![image](https://user-images.githubusercontent.com/43963760/209112139-9f91f0b8-8cae-4259-a525-daf666a42951.png)

**Comment by athensclub** [comment]
Is the Api working correctly in staging? When I tested in staging, I've sent a song with Santa/present emoji but in mysongs page, it is still showing shush emoji for every song. Not sure if this is on the Api or on the frontend code

**Comment by kithe-raker** [comment]
> @kithe-raker Is the Api working correctly in staging? When I tested in staging, I've sent a song with Santa/present emoji but in mysongs page, it is still showing shush emoji for every song. Not sure if this is on the Api or on the frontend code

my apologize, The staging webapp server is using production API. Totally forget about that will change it as soon as possible

**Comment by kithe-raker** [comment]
@athensclub I've just push the edited version in `develop` branch, merge with develop then redeploy the staging version again

**Comment by athensclub** [comment]
I'm outside right now, will look into it soon

**Comment by athensclub** [comment]
@kithe-raker I've just pushed the develop branch with few ui adjustments to staging, and now I can't log in. When I click log in with google, the log in tab pops up and immediately closes.

The console looks like this.
<img width="345" alt="image" src="https://user-images.githubusercontent.com/43963760/209344774-c18f5933-4320-46fe-ab6c-64a677c2a030.png">
<img width="350" alt="image" src="https://user-images.githubusercontent.com/43963760/209344827-27bf6e58-4711-46f6-b94d-a801de1a802f.png">
<img width="341" alt="image" src="https://user-images.githubusercontent.com/43963760/209344844-f3dc765d-4e44-485d-ac09-d51e83c86be6.png">

**Comment by kithe-raker** [comment]
> @kithe-raker I've just pushed the develop branch with few ui adjustments to staging, and now I can't log in. When I click log in with google, the log in tab pops up and immediately closes.
> 
> The console looks like this. <img alt="image" width="345" src="https://user-images.githubusercontent.com/43963760/209344774-c18f5933-4320-46fe-ab6c-64a677c2a030.png"> <img alt="image" width="350" src="https://user-images.githubusercontent.com/43963760/209344827-27bf6e58-4711-46f6-b94d-a801de1a802f.png"> <img alt="image" width="341" src="https://user-images.githubusercontent.com/43963760/209344844-f3dc765d-4e44-485d-ac09-d51e83c86be6.png">

Oh, yeah, I forget to whitelist the staging domain.
@athensclub try again.

**Comment by athensclub** [comment]
Are we using development api for the staging now?

**Comment by kithe-raker** [comment]
> Are we using development api for the staging now? @kithe-raker Is the production server ready for the new discs feature?

yeah, the production need to deploy the latest version

**Comment by athensclub** [comment]
I think we are ready to deploy, although this is from testing with development api. Although sometimes in My Songs page, when I select a song and the fetching playback url fails. This doesn't happen as much in staging though weirdly, or maybe I was making too many requests?
