### ISSUE TITLE
Urgent features after deploy

### ISSUE THREAD

**Issue by athensclub** [kithe-raker/gimmesong#95]
**DOD**
- [x] apple emoji for present box emoji image
- [x] fading text in share pattern number 4
- [x] flippable disc in song requests page

**Comment by athensclub** [comment]
Currently in staging. Should be ready to deploy soon. @kithe-raker are you still up? We might want to deploy this quickly after testing.

**Comment by athensclub** [comment]
Also, can we make the staging use the production Api now?

**Comment by athensclub** [comment]
No bugs found yet after a brief testing. I've created a PR for this task to deploy and have resolved all the conflicts. If you want to, you can deploy it. I will stay up until about 4-5 am and I might wake up really late. If there are any issues, I will **try** to be up as soon as possible tomorrow.

**Comment by kithe-raker** [comment]
> Also, can we make the staging use the production Api now?

I don't think we have to use production API on staging. If it's work on staging I think it's good to go.

**Comment by kithe-raker** [comment]
> No bugs found yet after a brief testing. I've created a PR for this task to deploy and have resolved all the conflicts. If you want to, you can deploy it. I will stay up until about 4-5 am and I might wake up really late. If there are any issues, I will **try** to be up as soon as possible tomorrow.

Merged.

**Comment by athensclub** [comment]
More tasks
 - [x] Fix unplayed song not flipped when played with button at bottom
 - [x] Layout adjustments to write message dialog (when sending songs)

**Comment by athensclub** [comment]
> More tasks
> 
> * [x]  Fix unplayed song not flipped when played with button at bottom
> * [x]  Layout adjustments to write message dialog (when sending songs)
> 
> Currently deploying in staging. Going to test it now

@kithe-raker I've tested the above task briefly in staging, found it working as expected. I've created a PR https://github.com/kithe-raker/gimmesong/pull/99 of the task to deploy to production if we're ready.

**Comment by athensclub** [comment]
I've just noticed a cleaner way to implement playing songs on disc flip. This will not directly use the autoplay settings which is the cause of a weird behavior that the site has to set autoplay to on when flipped and then set back to the previous setting after the song is played (which will result in weird toggle button toggling by itself). This would fix the problem. Currently is in staging right now.
